[features]
seeds = false
skip-lint = false
[programs.devnet]
gaurd = "GaUrdNt59ULmP6jjrHao6wpgw88AARkForCrTSvkw7CL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/loser/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
