[features]
seeds = false
skip-lint = false
[programs.devnet]
counter = "CntRxF2Ln5VV98F4ABzKYXPNmNkKEmHCaW9HEBCRSDfs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
# wallet = "/Users/loser/.config/solana/id.json"
wallet = "/Users/loser/projects/degen-toy-machine/wallets/SEA1xkZzPCUJBb5mcNb6ts9VExNr2kYMit3T5poqr94.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
